### ISSUE TITLE
Performance issue Bobs logistics mods

### ISSUE THREAD

**Issue by jgoyvaerts** [modded-factorio/bobsmods#146]
Currently playing a run of Seablock, savefile is here: 
[SeablockNovember2023.zip](https://github.com/modded-factorio/bobsmods/files/13506387/SeablockNovember2023.zip)

When me or my partner try to place a blueprint inside blueprint sandbox, the game freezes for several seconds on either side, causing it to become almost unplayable.

I've managed to trace it down to Bobs logistics mod, by enabling and disabling individual mods.

Repro steps:
- Load the save file
- Go into Blueprint sandbox (SHIFT+B or use the toolbar button)
- Place this blueprint: 
[slowblueprint.txt](https://github.com/modded-factorio/bobsmods/files/13506463/slowblueprint.txt)
- Observe how the game freezes for X seconds
- Disable Bobs logistics mods and reload the save
- Place the blueprint again, no freeze

I've also noticed removing the train lights from the blueprint removes the freeze as well.

Let me know if you need any more input!

**Comment by KiwiHawk** [comment]
I was able to reproduce the issue. However I don't think it's Bob's Logistics that is causing it. The lag is caused by all your trains repathing (possibly multiple times, not sure on this point). Removing Bob's Logistics mod deleted almost all of your trains, so there was nothing to repath.

I removed a lot of the mods from the save, to try narrow things down. I could reproduce the issue without blueprint sandbox. Instead, I'd just enable the map editor `/editor` and paste down the blueprint. In my tests, it was taking 30s to place the blueprint and 60s to undo it.

LTN also seems to be affecting it. I used an upgrade planner to replace all LTN stops with regular train stops. Then removed LTN mod. The lag was still there but for almost exactly half the time.


I understand how annoying this lag must be. Unfortunately I don't think there's much more than I can do to help sorry. It seems like it's a combination of vanilla train repathing plus LTN.
