### ISSUE TITLE
Circular Dependency

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#150]
Circular dependency between Bob's Logistics, Krastorio 2 and Space Exploration.

https://mods.factorio.com/mod/boblogistics/discussion/6586150c141dd2ab5a76b520

**Comment by Qatavin** [comment]
Looks like this is far from the only problem. I didn't test my SE integration with K2 also. I'm fixing that now.

**Comment by Qatavin** [comment]
For this particular issue, the loop is this:

boblogistics <- space-exploration <- Krastorio2 <- Squeak Through <- WideChests <- boblogistics

It was the addition of boblogistics <- space-exploration that created the loop. Removing it is not really an option if the integration is going to work. All I can suggest is for them to try to do without either Squeak Through or WideChests/Merging Chests. Merging Chests seems unnecessary to have when you've got AAI and K2 containers, so that's what I would nix.

**Comment by KiwiHawk** [comment]
K2 depending on Squeak Through seems unusual to me. I wonder why that is? 🤔
I'll ask them about it

**Comment by Brilliand** [comment]
Bobsmods depending on SE seems strange to me.  Many of the bits of bobsmods are _ancient_ mods that other mods have a tendency to depend on.  I don't think you can realistically catch every little mod that depends on parts of bobsmods, so bobsmods shouldn't really be adding dependencies to _anything_ at this point.

A new 'glue' mod that fixes all the problems that crop up between bobsmods and SE seems like the way to go, to me.  (Especially if you're just tweaking things that were working relatively OK without the compatibility work.)

**Comment by Qatavin** [comment]
We certainly could still do that. Deprecate at least most of the changes I made and make a new mod with them.

**Comment by KiwiHawk** [comment]
Fixed on the Krastorio 2 side by removing it's dependency on Squeak Through.

https://github.com/raiguard/Krastorio2/commit/92a6fc710c2423269165305de9057e3d6efd7471
