### ISSUE TITLE
How to hide/disable the sidebar window for 'adjustable inserters'?

### ISSUE THREAD

**Issue by SanderBouwhuis** [modded-factorio/bobsmods#155]
See screenshot.
I want to get rid of that useless clutter.
I only want to see the popup to configure inserters when I actually click on them.
I don't know where/which settings to change. Please help.

![2024-01-02 21-54-19 3840x2160 Factorio_1 1 100](https://github.com/modded-factorio/bobsmods/assets/10495173/0d4e059a-e14b-4c20-ae1f-ffc4083b8144)

**Comment by KiwiHawk** [comment]
This button here will hide that panel:

![image](https://github.com/modded-factorio/bobsmods/assets/59639/abfff509-99c2-45b0-9e74-5865a044d954)

If you aren't seeing this button, it's probably because you have it disabled in mod settings:
![image](https://github.com/modded-factorio/bobsmods/assets/59639/9c88c7e3-68fa-4a15-bb94-e9e957ee6f57)

------

1. Enable the button in mod settings
2. Click the button to hide the unwanted panel
3. Disable the button again in mod settings

**Comment by SanderBouwhuis** [comment]
Woooooooooow! I would never have figured this out without your help.

Thanks a lot!!!
