### ISSUE TITLE
Fluidbox Symetry

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#166]
https://factorio.com/blog/post/fff-394

In Factorio 2.0, machines will natively be flippable if they have a line of symmetry. The following machines currently do not:
- Stone Chemical Furnace
- Steel Chemical Furnace
- Fluid Burning Chemical Furnace
- Electronics Assembling Machine 2
- Electronics Assembling Machine 3

![image](https://github.com/modded-factorio/bobsmods/assets/59639/7d244e26-b1c8-48d9-b782-3aaa868b248d)

**Comment by Qatavin** [comment]
It seems like it would require assistance from the devs themselves to properly solve this issue. In order to make a 2x2 machine symmetrical, there would have to be two fluid boxes on each side. But that would be cluttered and ugly. It would be better if only one fluid connector would appear at a time (capable of being flipped by f or g keys) if there were only one fluid input/output in the recipe, but as far as I know, the game isn't set up to allow that.

**Comment by Qatavin** [comment]
It's occurred to me that there _might_ be a case where this could be made to work. It would depend on if the game considers inputs and outputs to be interchangeable for this kind of thing, though. However, considering that SE's space manufactory is accounted for in the code, I think there's at least a chance that this would work. What if we put a second fluid box on the same side of the machine as the first one, but make it an output? It should be hidden if there are no fluid outputs on the recipe, and indeed, there are no such recipes that any of these machines can even use.
