### ISSUE TITLE
Robot tiers

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#180]
# Bot Brain Recipes

### T4
- Mech brain
- Logistic robot brain brain 4
- Construction robot brain 4
- Combat robot brain 4
![image](https://github.com/modded-factorio/bobsmods/assets/59639/d7040b10-0e99-4c8d-8589-6976b6f410ee)

### T3
- Brain 2 (player)
- Logistic robot brain brain 3
- Construction robot brain 3
- Combat robot brain 3
![image](https://github.com/modded-factorio/bobsmods/assets/59639/bd6cbd74-3d21-49e7-b3e5-1ca1f9d99232)

### T2
- Brain (player)
- Logistic robot brain brain 2
- Construction robot brain 2
- Combat robot brain 2
![image](https://github.com/modded-factorio/bobsmods/assets/59639/1814ac2e-ce56-4e1c-bc2a-177c10ebcc8d)

### T1
- Logistic robot brain brain 1
- Construction robot brain 1
- Combat robot brain 1
![image](https://github.com/modded-factorio/bobsmods/assets/59639/79a416e7-db18-4bfc-96a7-260c31ccab0b)

# Fixes
- Remove CPUs from Brain 2 recipe
- Replace Superior circuit board (blue) with Circuit board (red) in Brain recipe
- Remove Integrated electronics from Brain recipe
- Replace Circuit board (red) with Basic circuit board (yellow) in Logistic robot brain 1 and Construction brain 1 recipes
- Remove Transistors from Logistic robot brain 1 and Construction brain 1 recipes
- Adjust prerequisites to suit

# Armour

## Current

![image](https://github.com/modded-factorio/bobsmods/assets/59639/29f3e50b-3380-4cd3-acdb-161380f66f44)

Without Bob's Technology mod:
- Modular armour: Red, Green
- Power armour: Red, Green, Blue
- Power armour 2: Red, Green, Military, Blue, Yellow
- Power armour 3: Red, Green, Military, Blue, Yellow
- Power armour 4: Red, Green, Military, Blue, Yellow
- Power armour 5: Red, Green, Military, Blue, Yellow

## Fixes

![image](https://github.com/modded-factorio/bobsmods/assets/59639/8bb51039-f5f1-4c54-98bf-74ac314d0b39)

- Modular armour: Red, Green
- Power armour: Red, Green, Military
- Power armour 2: Red, Green, Military, Blue
- Power armour 3: Red, Green, Military, Blue, Pink
- Power armour 4: Red, Green, Military, Blue, Purple, Pink, Yellow
- Power armour 5: Red, Green, Military, Blue, Purple, Pink, Yellow, Space

# Roboports

## Current
Roboport antenna array 1 and 2 both use Electronic circuit board
Roboport charging pad 1 and 2 both use Electronic circuit board

![image](https://github.com/modded-factorio/bobsmods/assets/59639/06e86ede-60d3-42f2-9173-05a90bc6a853)

## Fixes
- Replace Electronic circuit board (red) with Basic electronic board (yellow) in T1 antenna and charging pad recipes

# Other
Personal roboport robot control and Vehicle roboport robot control also need to take a lower tier of electronics.

**Comment by KiwiHawk** [comment]
Make sure portable solar doesn't use red circuits, even without Bob's Personal Equipment mod.

**Comment by Qatavin** [comment]
A lot seems to have been happening here while I haven't been paying attention. I have some thoughts on this, but I'll put the ones about bots in a different thread.

I would petition to have the changes to character brains reverted, other than to have Brain 2 use purple multi-layer circuit boards instead of blue superior circuit boards. Even though the other materials used in both tiers of character bodies are relatively low tech compared to the brains, I feel that the old way still works because it gives you something cool you can do right away as soon as you're ready to make blue and purple circuits, respectively, without having to set up anything else in terms of mines and material processing. For that reason, keeping everything in the same tech/material tier isn't really necessary, though regardless of whether bodies 1 is on red or blue circuit tier, some of the steel could definitely be exchanged for red-tier materials like cobalt steel and brass.

The other main reason I think it would be better to leave character bodies on the blue and purple circuit board tiers is because it feels like there's a lack of capability-expanding features in that phase of the game. Trains, robotics, modules, beacons, and solar power can all be unlocked in the red tier. Spidertrons aren't until the green tech tier. Pretty much the only big thing in the blue tech tier is artillery. There's a tendency with Bob's Mods and their upgrade-centric design to want to push things forward in the tech tree, but bodies, I think, should stay further down.

**Comment by KiwiHawk** [comment]
- Character bodies tech requires Red, Green, and Blue science
- Character bodies 2 tech requires Red, Green, Blue, and Purple science
- Walking vehicle tech (Antron) requires Red, Green, Military, Blue, and Purple science

With the change you are suggesting, Brain 2 and Mech brain would take the same ingredients. I think of the character bodies and *trons as filling similar roles. So it make sense to me that there's a progression, from one to the other.

> The other main reason I think it would be better to leave character bodies on the blue and purple circuit board tiers is because it feels like there's a lack of capability-expanding features in that phase of the game. Robotics, modules, beacons, and solar power can all be unlocked in the red tier or even earlier. Spidertrons aren't until the green tech tier. Pretty much the only big thing in the blue tech tier is artillery. There's a tendency with Bob's Mods and their upgrade-centric design to want to push things forward in the tech tree, but bodies, I think, should stay further down.

I'm confused! This sounds like an argument **for** my changes. With my change, Brain uses the same tier of circuit board as artillery (rather than one tier higher). The science packs required for the character bodies haven't changed. Reducing the circuit board tier required for brains puts them more firmly in that gap that you referred to.

> On the matter of changing tier 1 roboports and such to use yellow circuit boards, I'm not sure if that really works. Aside from the fact that yellow boards kinda feel too simple for this purpose, it has to be noted that robots of this tier still require electric engine units, which in turn require lubricant, and therefore oil. This change would mean that you could put red boards on hold to set up robots first, but that is all. However, I would say that compared to my firm opposition to the other changes that have been made, I'm merely dubious about this.

Previously, it felt that T1 and T2 Robots were unlocked very close to each other. I believe that this change helps space them out a bit more. Yes, oil is required. For lubricant as well as batteries (plastic + sulfuric acid), so bots aren't unlocked too early. Not a huge difference, but I believe it is an improvement.

Old:
![image](https://github.com/modded-factorio/bobsmods/assets/59639/76682e67-b57e-4539-8623-20fbae4b0faa)

New:
![image](https://github.com/modded-factorio/bobsmods/assets/59639/eb39adb3-6b64-4539-bc86-74af5ade204b)

**Comment by Qatavin** [comment]
> * Character bodies tech requires Red, Green, and Blue science
> * Character bodies 2 tech requires Red, Green, Blue, and Purple science
> * Walking vehicle tech (Antron) requires Red, Green, Military, Blue, and Purple science
> 
> With the change you are suggesting, Brain 2 and Mech brain would take the same ingredients. I think of the character bodies and *trons as filling similar roles. So it make sense to me that there's a progression, from one to the other.

In terms of progression, I would think that it's enough to have T1 bodies lead into both Spidertrons and T2 bodies. Getting T1 bodies gives you the ability to be in many places at once. T2 bodies are just a bit of a nice upgrade. Thus, having the latter be more or less side by side with Spidertrons is fine.

> I'm confused! This sounds like an argument **for** my changes. With my change, Brain uses the same tier of circuit board as artillery (rather than one tier higher). The science packs required for the character bodies haven't changed. Reducing the circuit board tier required for brains puts them more firmly in that gap that you referred to.

Sorry, I worded that in an unclear way. I meant blue circuit board tier. Because while artillery uses red boards, the artillery remote uses blue boards. Sure, you don't need to use a remote, but it does push artillery down the tech tree a bit more.

> Previously, it felt that T1 and T2 Robots were unlocked very close to each other. I believe that this change helps space them out a bit more. Yes, oil is required. For lubricant as well as batteries (plastic + sulfuric acid), so bots aren't unlocked too early. Not a huge difference, but I believe it is an improvement.

Okay, I've come around on this. I've realized that with a few more adjustments, it would be possible to make T1 robots without needing oil at all. With my own mod, I've always tried to look for ways to make oil _not_ the absolute, nearly forced first choice for non-starter materials to get. This would go a long way toward making that a reality.

**Comment by Qatavin** [comment]
I've been experimenting with tier 1 logistic bots using only yellow circuit boards in my own mod, and I have succeeded at rearranging things so that they can be made with no oil at all. In the current tech tree, you have to go chemical plant->oil processing->sulfur processing before you can make batteries or research nickel, zinc, or lead processing. This order of techs treats crude oil as the principle source of sulfur production, but that doesn't necessarily need to be the case. Lead and nickel processing can both output sulfuric gases, so it's perfectly viable to move sulfur processing up the tree to be before oil processing or horizontally adjacent to it. I did have to replace the plastic in lead batteries with steel, but I can live with that.

The other hurdle to making oilless robots was of course the electric engine units, which normally require lubricant. Except in my mod, I have four tiers of electric motors, and only the last two use lubricant. Instead, the tier of electric motor that the earliest logistic bots use is gated behind either nickel or zinc, which are needed to make ferrite magnets. This effectively incentivizes players to try going for something other than oil first among the non-starter resources, as is typically the default. I've been trying to find a way to make that happen for a long time now.

**Comment by KiwiHawk** [comment]
Sounds interesting! I might do something similar for BA. It's easier there as "oil" products can come from bio sources.

Yeah, could definitely remove the requirement on oil for sulfur.

I'm not sure how well the other changes you mentioned would translate into core Bob's. As we don't have the additional engine tiers etc.

**Comment by Qatavin** [comment]
Right. This update is probably not a good time to make a major overhaul of intermediates, if the main aim here is just to be in harmony with 2.0 without Space Age. I figure it'll take months more to figure out how to integrate with Space Age, though, and maybe during that time we can consider a wider range of options. Just something to keep in mind for later.

**Comment by SGZ-Creations** [comment]
is the armour's: Invar-Cobalt & Titanium-Ceramics. Being removed. If yes could they at least me made in to intermediate chassis?
without Space Age 
Recipe concept 
![image](https://github.com/user-attachments/assets/0acfb6e3-2b34-4087-957e-51a527bf2769)
![image](https://github.com/user-attachments/assets/49eb07c5-d347-40df-bf4b-f82ee0a73068)
disregard all the other clutter please

Tech concept
![image](https://github.com/user-attachments/assets/97ae389c-1762-4fbf-a1aa-e313fa800447)
![image](https://github.com/user-attachments/assets/f38bfacc-a776-41d4-a66a-cdf04c4bcc7b)
