### ISSUE TITLE
Mining drill color masks

### ISSUE THREAD

**Issue by Qatavin** [modded-factorio/bobsmods#188]
![new miner test](https://github.com/modded-factorio/bobsmods/assets/108201496/c13bdd81-2b41-4c26-acdf-0851262632e7)
![new miner test 2](https://github.com/modded-factorio/bobsmods/assets/108201496/c247a254-f354-4e10-8083-eae8039eecad)

I decided to make color masks for the mining drills because of a separate request someone made for the B+SE mod, but they seem like a good fit for baseline Bob's too, if this meets with approval. Colors are still up for revision, but I personally think they look better being not quite as bright and saturated as assembly machines etc. are.

The total size of all 18 required graphics files is only 63.4 KB.

I'd like to do new icons for them as well, but haven't finished them yet.

In the runup to 2.0, perhaps we should consider color masks for a few other things too, like oil refineries, and maybe even nuclear reactors. although in the latter case, their different heat pipes and working glow colors are probably good enough.

**Comment by KiwiHawk** [comment]
@Qatavin Have you seen [Artisanl Reskins: Bob's Mods](https://mods.factorio.com/mod/reskins-bobs) ? Kira has done a lot of work on reskinning already. I can't remember which entities he still hasn't touched yet.

**Comment by Qatavin** [comment]
I have checked it out, and it adds color to the drill unit on top of the miners, but not to the cladding in the front. There's no conflicts between the two additions, so I'd say we're good to go with this.

On the topic of Artisanal Reskins in general, while I do greatly enjoy vibrantly colorful things, and there are certain graphics that I'm wondering if we could ask to port over (artifacts, glass, small fluid tanks, bullet components, and plenty of others), I find that a lot of the revised entity graphics are a little _too_ colorful, to the point that they start to look... un-industrial, or toy-like, is how I suppose I would put it. Large fluid tanks, steam engines, and nuclear reactors would be examples of that, where I would favor a more subtle style to make the coloration an accent, and not so in-your-face.

**Comment by KiwiHawk** [comment]
Yeah, definitely agree about the over colourful thing! @kirazy How do you feel about porting some of the graphics into Bob's directly?

**Comment by kirazy** [comment]
I'm not necessarily opposed.

Some reasons I chose not to do the miner masks the way they are done in this suggestion:
- Bob's has two classes of miner's, large-area and standard. I differentiate those by changing the color of the frame. Here, the only discernible difference is very slight changes in shading between equivalent tiers.
- One of the guiding philosophies for AR color masks was that the colored parts are never a pipe, a cable, a strut, a beam, or an industrial bit. It is, wherever possible, the "metal casing". This does occasionally mean that some buildings are... particularly vibrant. But the goal was consistency in the visual language. Also, the metal casing tends to be the rusted bits which makes things visually interesting.

It may be simpler to augment AR with additional options/color masks to provide the desired coloration. That maintains the cross-mod compatibility with supporting mods and e.g. Angel's.

I had been idly-dreaming of breaking out the masks into a resource-pack-type thing consumed like a library by other mods, with methods that can be called to skin various entities however a mod desires. AR would then become a consumer mod that uses the assets indirectly, rather than host the assets. That may be a preferred approach. Then bobs can use all the masks in AR without the AR logic.

**Comment by Qatavin** [comment]
Fortunately, it's not like everything _has_ to be colored in the same way. While Bob's uses a color-by-tier approach generally, a few things like roboports are exceptions (setting aside the stuff that doesn't have tier-specific coloration at all), and that works just fine. In the case of storage tanks, recoloring them to resemble the pipes made from the same materials seems like a perfectly workable solution.

As for the large area mining drills, there is certainly more than can be done to differentiate them, and I do plan to keep working on that.

What I'm really hoping for is for us to be able to replace a lot of the old, outdated sprites with the excellent, snazzy AR ones. In particular, the sprites for...

-  The new ammo types from Warfare, especially the rockets, as well as all of the bullets, bullet projectiles, and other ammo components.
- The laser robot (along with its entity sprites).
- Alien artifacts and science packs.
- Glass.
- Zinc plate.
- Pretty much anything with item sprites that currently look the same on every tier.
- And probably a bunch of others.

**Comment by KiwiHawk** [comment]
Looks good to me!

**Comment by Qatavin** [comment]
![new storage tank test](https://github.com/user-attachments/assets/fa9cc46d-66ed-4686-ada0-991af04f811d)

Threw this together fairly quick. I'm not totally happy with the colors, but I think the masks are pretty good.

**Comment by Qatavin** [comment]
This has been applied and merged
