### ISSUE TITLE
Update for Factorio 2.0

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#189]
- [x] Remove `normal` and `expensive` from recipes and technology
- [x] Remove `result` / `result_count` from recipes (use `results` instead)
- [x] Remove short syntax (`{"item-name", 39}`) for item products
- [x] Remove short syntax for item ingredients. Type is now required
- [x] Update all catalyst recipes.
- [x] Check prototype names

> For 2.0, recipe prototypes are unified so that normal and expensive are no longer a thing ([viewtopic.php?p=577191#p577191](https://forums.factorio.com/viewtopic.php?p=577191#p577191)).
[Furthermore](https://discord.com/channels/139677590393716737/306402592265732098/1171060349185839164), result and result_count have been removed so only results is allowed. Also, the short syntax ({"item-name", 39}) for ItemProductPrototype was removed.
Bilka

> Bilka made an executive decision, IngredientPrototype will no longer support short syntax. IngredientPrototype's type will be mandatory. Those changes will be released with 2.0.
> 
> To not mess up with technologies, since technologies only support items they wont be using IngredientPrototype but instead will be using ResearchIngredient that only supports short syntax (at prototype stage).
> 
> However MinableProperties result/count... it an extremally controversial change

https://forums.factorio.com/viewtopic.php?p=615188#p615188

> Separate the 2 functions of "catalyst_amount" into 2 parameters
> This has been implemented for 2.0 as ignored_by_productivity and ignored_by_stats. Additionally, the auto-detection of catalysts has been removed.
> catalyst_amount is removed in 2.0.
<https://forums.factorio.com/viewtopic.php?p=615440#p615440>

> Prototype names are being limited to the characters: AZaz09_- <https://forums.factorio.com/viewtopic.php?f=34&t=114525>

**Comment by Qatavin** [comment]
Another unforeseen issue that needs addressing:

When a recipe only has a single result, the game used to assign the result's name to the recipe for locale purposes. Not any more. Now the game only does this when the recipe's name is an exact match for the result's name. The reason for this seems to have to do with the Factoriopedia. Recipes with the same name as their result are now taken to be the official recipe and displayed at the top of the Factoriopedia page for a given item or fluid (though if they have multiple outputs, they need "main_product" as well in order to be "official"), with all others being "alternative". Having all recipes be "alternative" isn't too terrible, though. You can still click on them to see the recipe details. So maybe we should rename recipes to match their outputs, or maybe we don't. I don't have a particular recommendation for that. One interesting thing to note is that recycling does _not_ prioritize the official recipe. It seems the recipe that is defined _first_ will be the one that is used.

Related to this, the recycler's recipes do not take into account changes made to recipes after the data stage. If a recipe is changed in the data-updates or data-final-fixes stage, the recycling recipe will also need to be updated to match.
