### ISSUE TITLE
Review Turret Tiers

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#84]
T3, T4, and T5 turrets are basically the same apparently. Except for 1 increased range.

Reported on Angel's discord.

**Comment by Qatavin** [comment]
They aren't the same. They have a damage multiplier which does not show up in their tooltips.

Testing in sandbox mode indicates that with all techs unlocked (physical projectile damage researched to level 7) the damage output per shot of these turrets with uranium ammo is:

T1: base 24 + (24 * 1.6(ammo damage multiplier) = 38.4) = 62.4 * 2.9(turret damage multiplier) = 180.96, which the game renders as 24+157
T2: base (24*1.25 = 30) + (30 *1.6 = 48) = 78 * 2.9 = 226.2, or 30 + 196
T3: base (24*1.5 = 36) + (36 *1.6 = 57.6) = 93.6 * 2.9 = 271.44, or 36 + 235
T4: base (24*1.75 = 42) + (42 *1.6 = 67.2) = 109.2 * 2.9 = 316.68, or 42 + 275
T5: base (24*2 = 48) + (48 *1.6 = 76.8) = 124.8 * 2.9 = 361.92, or 48 + 314

**Comment by Qatavin** [comment]
Higher tier turrets could be improved by increasing their deploy speed and/or rotation speed. Also by giving them a prepare_range so that they deploy before the enemy enters firing range.

I would also suggest increasing the health on gun turrets to 400 * level, because with only 800 on the T5s, their survivability against Rampant enemies is kind of lacking. It would make sense to reduce the health on sniper turrets, though. Given their nature, it would make sense for them to be more fragile.
