### ISSUE TITLE
SE Compatibility

### ISSUE THREAD

**Issue by KiwiHawk** [modded-factorio/bobsmods#88]
From Discord:
- Express Inserters don't need space science even though the infra tech that is a perquisite does.
- Personal Battery techs make very little sense. MK2 requires some pretty advanced materials and science, but everything after that is just 2 older batteries and 5 batteries to glue them together, and all use the same science packs.

### Additional suggestions:
https://docs.google.com/document/d/113rB1-6N7QN9Qp6GSDwERVBX9BlcB4m8AyvQAj-iy7U/edit

**Comment by Qatavin** [comment]
The Express Inserter thing is an issue with the Space Exploration side. The problem seems to come from the changes to the tech structure made in SE version 0.6. I'm pretty sure it was only in this version that the space science pack was added to the logistics 3 tech. I guess they just haven't gotten around to updating the integration through whatever functions they use. It would be a trivial matter to simply add the space science pack to the express inserters and stack inserter 2 techs using bobmods.lib.tech.add_science_pack([techname], "space-science-pack", 1) when Space Exploration is active. The personal battery thing is a considerably more complicated question.

If you're jumping down the rabbit hole of SE and AAI integration, I'd suggest going all the way with it, not just doing a couple minor fixes. For quick reference, Space Exploration is compatible with the following Bob's mods:

Adjustable Inserters
Assembling
Classes
Enemies
Greenhouse
Logistics
Mining
Personal Equipment

And incompatible with these:

Electronics
Modules
Ores
Plates (MCI)
Power
Revamp
Tech
Vehicle Equipment
Warfare

SE also has high-level integration with Krastorio 2, which is incompatible with Bob's Personal Equipment. Note that AAI Industry, which is part of the SE suite, has a small amount of integration with Bob's mods, primarily Logistics, which should also be accounted for going forward.

Recently, while working on my personal Bob's expansion (Qatmore) I looked at adding AAI integration. This ended up being quite a project, which spiraled out of control until I kind of ended up doing a total overhaul of the whole suite. A sort of advanced recipes mode. AAI Industry is pretty modest on its own, but the way it uses electric motors in a much broader range of recipes has a lot of implications, considering how upgrade-oriented Bob's mods are. Anyway, since I've done so much work on the subject already, I can write up some simple suggestions along these lines.

**Comment by KiwiHawk** [comment]
Yes, some suggestions would be useful and appreciated! Thanks

**Comment by Qatavin** [comment]
These would be some of my suggestions for SE-integrated recipes. I've only gone through Assembly and Logistics so far, though. They're designed to follow the vein set by recipes in SE itself, and they assume that Bob's Ores and Plates are not going to be available, since they are currently designated as incompatible. It kind of makes my brain hurt to think about what it would take to reconcile the loosely tier-based Bob's Ores with the branching structure of SE's ores.

-------------------Assembly-------------------

Assembling 4: (Needs crafting categories: basic-crafting, advanced-crafting, crafting-or-electromagnetics)
-4 big electric motor
-8 advanced circuit
-6 iridium plate
-4 heavy girder
-2 inserter
-1 assembling 3

Assembling 5: (Needs crafting categories: basic-crafting, advanced-crafting, crafting-or-electromagnetics)
-4 big electric motor
-4 heavy bearing
-3 processing unit
-8 refined concrete
-2 fast inserter
-1 assembling 4

Assembling 6: (Needs crafting categories: basic-crafting, advanced-crafting, crafting-or-electromagnetics)
-4 heavy assembly
-1 quantum processor
-2 nanomaterial
-1 stack inserter
-8 lubricant
-1 assembling 5

Electronics machine 1: (3 modules) (Needs crafting categories: crafting-or-electromagnetics)
-2 small electric motor
-5 electronic circuit
-5 iron plate

Electronics machine 2: (4 modules) (Needs crafting categories: crafting-or-electromagnetics)
-3 big electric motor
-8 processing unit
-5 iridium plate
-1 electronics machine 1

Electronics machine 3: (6 modules) (Needs crafting categories: crafting-or-electromagnetics)
-5 big electric motor
-1 quantum processor
-1 fast inserter
-4 self-sealing gel
-1 electronics machine 2

Space electronics machine: (4 modules)
-2 big electric motor
-5 processing unit
-4 low density structure
-2 heat shielding

Chemical plant 1:
-2 pump
-5 electronic circuit
-5 pipe
-5 stone brick
-5 glass
-5 steel plate

Chemical plant 2:
-2 pump 2
-5 advanced circuit
-6 heat shielding
-6 pyroflux
-1 chemical plant 1

Chemical plant 3:
-2 pump 3
-10 processing unit
-4 bioscrubber
-5 iridium pipe
-1 chemical plant 2

Chemical plant 4:
-2 pump 4
-1 quantum processor
-1 lattice pressure vessel
-1 chemical plant 3

Centrifuge 2:
-50 iridium plate
-20 heavy bearing
-20 holmium solenoid
-100 refined concrete
-1 centrifuge 1

Centrifuge 3:
-20 nanomaterial
-20 superconductive cable
-5 quantum processor
-1 centrifuge 2

Oil refinery 1:
-15 small electric motor
-4 pump 1
-10 electronic circuit
-15 iron pipe
-15 stone brick
-15 glass
-15 steel plate

Oil refinery 2:
-10 big electic motor
-4 pump 2
-10 advanced circuit
-10 heat shielding
-20 concrete
-1 oil refinery 1

Oil refinery 3:
-10 big electic motor
-4 pump 3
-10 processing unit
-20 iridium plate
-10 iridium pipe
-1 oil refinery 2

Oil refinery 4:
-10 big electic motor
-4 pump 4
-2 quantum processor
-3 lattice pressure vessel
-5 heavy composite
-1 oil refinery 3

Electric furnace 2: (Power: 225kW)
-1 electric furnace
-5 processing unit
-10 iridium plate
-10 iridium girder
-3 heat shielding

Electric furnace 3: (Power: 300kW)
-1 electric furnace 2
-5 processing unit
-10 heavy composite
-1 hot thermodynamics data
-1 experimental alloys data

-------------------Logistics-------------------

Pump 2:
-2 big electric motor
-2 steel pipe
-1 Pump 1

Pump 3:
-2 iridium plate
-2 iridium pipe
-1 Pump 2

Pump 4:
-1 self-sealing gel
-1 lattice pressure vessel
-1 Pump 3

Storage tank 1 all:
-24 iron plate
-5 steel plate

Storage tank 2:
-20 beryllium plate
-5 low density structure
-1 storage tank 1

Storage tank 2 all:
-24 beryllium plate
-5 low density structure
-1 storage tank 1 all

Storage tank 3:
-20 iridium plate
-4 heavy girder
-1 storage tank 2

Storage tank 3 all:
-24 iridium plate
-4 heavy girder
-1 storage tank 2 all

Storage tank 4:
-4 heavy composite
-2 lattice pressure vessel
-1 storage tank 3

Storage tank 4 all:
-5 heavy composite
-2 lattice pressure vessel
-1 storage tank 3 all

Logistic chest 1:
-1 steel chest
-4 advanced circuit

Logistic chest 2:
-1 logistic chest 1
-4 advanced circuit
-4 heavy girder

Logistic chest 3:
-1 logistic chest 2
-4 processing unit
-1 heavy composite

Locomotive 2:
-10 big electric engine
-6 heavy bearing
-10 advanced circuit
-1 locomotive 1

Locomotive 3:
-4 heavy assembly
-2 aeroframe bulkhead
-10 processing unit
-1 locomotive 2

Armored locomotive 1:
-15 steel plate
-2 low density structure
-1 locomotive 1

Armored locomotive 2:
-12 big electric engine
-6 heavy bearing
-10 heavy composite
-10 advanced circuit
-1 armored locomotive 1

Cargo wagon 2:
-4 heavy bearing
-8 heavy girder
-1 cargo wagon 1

Cargo wagon 3:
-2 aeroframe bulkhead
-4 heavy composite
-1 cargo wagon 2

Armored cargo wagon 1:
-15 steel plate
-2 low density structure
-1 cargo wagon 1

Armored cargo wagon 2:
-4 heavy bearing
-8 heavy composite
-1 armored cargo wagon 1

Fluid wagon 2:
-4 heavy bearing
-2 heavy girder
-1 storage tank 2
-1 fluid wagon 1

Fluid wagon 3:
-2 aeroframe bulkhead
-2 heavy composite
-1 storage tank 3
-1 fluid wagon 2

Armored fluid wagon 1:
-15 steel plate
-2 low density structure
-1 fluid wagon 1

Armored fluid wagon 2:
-4 heavy bearing
-8 heavy composite
-1 storage tank 3
-1 armored fluid wagon 1

Flying robot frame 2:
-4 big electric motor
-4 battery
-4 advanced circuit
-2 berylium plate

Flying robot frame 3:
-4 big electric motor
-6 battery
-4 advanced circuit
-2 aeroframe scaffold

Flying robot frame 4:
-6 holmium solenoid
-8 battery
-4 processing unit
-2 aeroframe scaffold

Flying robot frame 2 base:
-1 big electric motor
-2 battery
-3 advanced circuit
-1 steel plate

Flying robot frame 3 base:
-1 big electric motor
-2 battery
-3 processing unit
-1 steel plate

Flying robot frame 4 base:
-1 big electric motor
-2 battery
-3 processing unit
-1 steel plate

Construction robot tool 1:
-3 iron gear wheel
-1 steel plate

Construction robot tool 2:
-3 iron gear wheel
-1 beryllium plate

Construction robot tool 3:
-3 iron gear wheel
-1 aeroframe scaffold

Construction robot tool 4:
-2 holmium solenoid
-1 aeroframe scaffold

Logistic robot tool 2:
-2 iron gear wheel
-1 beryllium plate

Logistic robot tool 3:
-2 iron gear wheel
-1 aeroframe scaffold

Logistic robot tool 4:
-1 holmium solenoid
-1 aeroframe scaffold

Roboport antenna 1:
-25 electronic circuit
-10 copper cable
-4 steel plate

Roboport antenna 2:
-10 advanced circuit
-20 copper cable
-4 aeroframe pole

Roboport antenna 3:
-5 processing unit
-6 holmium cable
-4 aeroframe pole

Roboport antenna 4:
-1 quantum processor
-2 superconductive cable
-1 low density structure

Roboport hatch 1:
-20 iron gear wheel
-20 small electric motor
-30 steel plate

Roboport hatch 2:
-20 iron gear wheel
-30 small electric motor
-30 beryllium plate

Roboport hatch 3:
-20 iron gear wheel
-10 big electric motor
-15 aeroframe scaffold

Roboport hatch 4:
-20 iron gear wheel
-15 big electric motor
-10 aeroframe bulkhead

Roboport charging pad 1:
-2 battery
-4 copper cable
-5 electronic circuit
-10 steel plate

Roboport charging pad 2:
-4 battery
-8 copper cable
-10 advanced circuit
-10 beryllium plate

Roboport charging pad 3:
-6 battery
-4 holmium cable
-5 processing unit
-5 aeroframe scaffold

Roboport charging pad 4:
-8 battery
-2 superconductive cable
-1 quantum processor
-3 aeroframe bulkhead

Roboport 2: steel plate -> 15 beryllium plate
Roboport 3: steel plate -> 10 aeroframe scaffold
Roboport 4: steel plate -> 5 aeroframe bulkhead
Logistic zone expander 2: steel plate -> 10 aeroframe pole
Logistic zone expander 3: steel plate -> 6 aeroframe scaffold
Logistic zone expander 4: steel plate -> 3 aeroframe bulkhead
Robochest 2: steel plate -> 8 beryllium plate
Robochest 3: steel plate -> 5 aeroframe scaffold
Robochest 4: steel plate -> 2 aeroframe bulkhead
Robot charging point 2: steel plate -> 7 beryllium plate
Robot charging point 3: steel plate -> 4 aeroframe scaffold
Robot charging point 4: steel plate -> 2 aeroframe bulkhead
Large robot charging point 2: steel plate -> 15 beryllium plate
Large robot charging point 3: steel plate -> 10 aeroframe scaffold
Large robot charging point 4: steel plate -> 5 aeroframe bulkhead

1 transport belt:
-1 basic transport belt
-1 small electric motor
-2 iron plate

1 fast transport belt:
-1 transport belt
-2 iron gear wheel
-1 steel plate

1 express transport belt:
-1 fast transport belt
-4 iron gear wheel
-10 lubricant

4 turbo transport belt:
-4 express transport belt
-2 big electric motor
-1 aeroframe scaffold

4 ultimate transport belt:
-4 turbo transport belt
-1 heavy bearing
-2 holmium cable

2 underground belt:
-6 transport belt
-2 small electric motor
-10 iron plate

2 fast underground belt:
-2 underground belt
-24 iron gear wheel
-16 steel plate

2 express underground belt:
-2 fast underground belt
-64 iron gear wheel
-120 lubricant

2 turbo underground belt:
-2 express underground belt
-10 big electric motor
-5 aeroframe scaffold

2 ultimate underground belt:
-2 turbo underground belt
-6 heavy bearing
-12 holmium cable

1 splitter:
-2 transport belt
-5 electronic circuit
-5 iron plate

1 fast splitter:
-1 splitter
-5 electronic circuit
-8 steel plate
-10 iron gear wheel

1 express splitter:
-1 fast splitter
-5 advanced circuit
-20 iron gear wheel
-20 lubricant

1 turbo splitter:
-1 express splitter
-5 processing unit
-2 big electric motor
-4 aeroframe scaffold

1 ultimate splitter:
-1 turbo splitter
-5 processing unit
-2 heavy bearing
-2 holmium cable

Inserter:
-1 burner inserter
-1 electronic circuit
-1 small electric motor

Turbo inserter:
-1 express inserter
-1 processing unit
-1 big electric motor
-2 aeroframe pole

Turbo filter inserter:
-1 express filter inserter
-5 processing unit
-1 big electric motor
-2 aeroframe pole

Turbo stack inserter:
-1 express stack inserter
-1 processing unit
-2 big electric motor
-2 aeroframe pole

Turbo stack filter inserter:
-1 express stack filter inserter
-6 processing unit
-2 big electric motor
-2 aeroframe pole

Ultimate inserter:
-1 turbo inserter
-1 processing unit
-1 heavy bearing
-1 holmium cable

Ultimate filter inserter:
-1 turbo filter inserter
-5 processing unit
-1 heavy bearing
-1 holmium cable

Ultimate stack inserter:
-1 turbo stack inserter
-1 processing unit
-1 heavy bearing
-2 holmium cable

Ultimate stack filter inserter:
-1 turbo stack filter inserter
-6 processing unit
-1 heavy bearing
-2 holmium cable

**Comment by KiwiHawk** [comment]
Thanks for that! Looks good 
I don't think I'll get this done for the next release. Aiming for the one after.

**Comment by mecejide** [comment]
Looks good. One thing I’d do is make each assembling machine use inserters in its recipe:
Burner assembling machine needs 2 burner inserters
Steam powered assembling machine needs 2 steam powered inserters
Assembling machine 1 needs 2 inserters
Assembling machine 2 needs 2 filter inserters
Assembling machine 3 needs 2 fast filter inserters
Assembling machine 4 needs 2 express filter inserters
Assembling machine 5 needs 2 turbo filter inserters
Assembling machine 6 needs 2 ultimate filter inserters

**Comment by Qatavin** [comment]
That would be a possibility. My suggestion to add inserters to assembling machines 4, 5, and 6 is meant to progress the current trend of of increasing complexity in SE. That is, space manufactories include fast inserters in their recipe, but assembling machines 1, 2, 3, and space do not. So, there's precedent in using inserters in this way, but I would suggest saving them for the higher tiers.

**Comment by mecejide** [comment]
Also, I don’t really see the problem with Bob’s Ores. It’s not like each advanced resource has to be aligned with a single science type.

**Comment by Qatavin** [comment]
I'd be concerned about what it would do to the pacing. In the current version of Bob's, if you just start mining materials in the order they're needed for science packs, transitioning from utility science to space science requires setting up mines and production lines for uranium, tungsten, silver, and nickel. That's a lot, but it works okay because this is the culmination of the game. But in SE, it's not even the midpoint. And production and utility science are moved to after space science, so it goes from chemical or logistic science straight to rocket science with only electronic boards in between as milestones, while adding titanium and gold (and maybe aluminium and zinc) to the list of elements you'd need to start mining. It's Space Exploration. You wanna hurry up and get to space. And having rockets be so incredibly complicated feels like it would diminish what comes afterwards. But then, they're _space rockets_. It doesn't make sense for them not to be one of the most complex things in the game. You see the contradiction in the design here?

Now, all that could be solved with enough work. But another issue would be the offworld outposts. You'd have this plethora of different resources littering the landscape. Offworld outposts don't need all that much input quantitatively, but they do need some fairly high-level intermediates like low density structures and heat shielding in order to ship their products. What an incredible pain it would be to set up titanium production on multiple worlds, including dealing with chlorine-sodium hydroxide gridlock. Ugh. But on the other hand, not having them or not needing them for the offworld portions, which represents a very sizeable percentage of the game, would make having them at all feel kinda pointless. Importing them is always an option, but being effectively forced to import them by all the logistical complications involved would negatively impact the gameplay of building these outposts, I feel.

Of course, all of this is moot if Bob's Ores remains blocked in SE's dependencies.

**Comment by Qatavin** [comment]
-------------------Greenhouse-------------------

The SE/Bob's design doc suggests making growth facilities able to produce wood using greenhouse recipes, but in my personal opinion, that's not the correct move. If there's one thing that should be more difficult to make in space, I'd think wood is it. Overall, I don't think Bob's Greenhouse needs any changes as things stand.

Unless something is added, that is. Something like using biological science to extract trace amounts of minerals from the soil. Like, using some form of vitamelange as a fertilizer to promote the growth of plants that can be harvested for basic ores. The use case would be if you have a world you want to build an outpost on, but it's short of something you need to make delivery capsules or what have you. If done right, this could be made to be more efficient than sending the missing resource directly, or it could save the trouble of setting up a local mine. It would be balanced by the fact that vitamelange processing is not that easy to scale up, so expending it in this way would only be worthwhile for the typically small-scale needs of offworld outposts. Or at least, that would be the idea.

-------------------Mining-------------------

Electric mining drill 1:-
-1 burner mining drill
-4 iron gear wheel
-4 small electic motor

Electric mining drill 2: (0.75/s mining speed) (127kW) (pollution 13)
-1 electic mining drill 1
-5 electronic circuit
-5 iron gear wheel
-10 steel plate

Electric mining drill 3: (1/s mining speed) (160 kW) (pollution 15)
-1 electic mining drill 2
-5 advanced circuit
-4 big electric motor
-20 lubricant

Electric mining drill 4: (1.5/s mining speed) (225 kW) (pollution 18)
-1 electic mining drill 3
-3 processing unit
-5 heavy girder
-5 heavy bearing

Electric mining drill 5: (2/s mining speed) (280kW) (pollution 20) (Add resource_categories: hard-resource)
-1 electic mining drill 4
-1 quantum processing unit
-3 heavy assembly
-1 dyanamic emitter

Electric large area mining drill 2: (0.75/s mining speed) (135kW) (pollution 13)
-1 electic mining drill 1
-6 electronic circuit
-6 iron gear wheel
-15 steel plate

Electric large area mining drill 3: (1/s mining speed) (170 kW) (pollution 15)
-1 electic large area mining drill 2
-6 advanced circuit
-5 big electric motor
-25 lubricant

Electric large area mining drill 4: (1.5/s mining speed) (240 kW) (pollution 18)
-1 electic large area mining drill 3
-4 processing unit
-7 heavy girder
-7 heavy bearing

Electric large area mining drill 5: (2/s mining speed) (300kW) (pollution 20) (Add resource_categories: hard-resource)
-1 electic large area mining drill 4
-1 quantum processing unit
-4 heavy assembly
-1 dyanamic emitter

Big mining drill: (2/s mining speed)
-1 electric mining drill 3
-8 big electric motor
-4 processing unit
-20 steel plate

Pumpjack 1:
-10 iron gear wheel
-10 small electic motor
-5 electronic circuit
-10 iron pipe
-10 steel plate

Pumpjack 2:
-1 pumpjack 1
-10 iron gear wheel
-5 advanced circuit
-10 steel pipe
-20 concrete

Pumpjack 3:
-1 pumpjack 2
-10 big electric motor
-5 advanced circuit
-10 plastic pipe
-10 lubricant

Pumpjack 4:
-1 pumpjack 3
-5 heavy bearing
-3 processing unit
-10 iridium pipe
-10 heavy girder

Pumpjack 5:
-1 pumpjack 3
-2 heavy assembly
-1 quantum processor
-2 self-sealing gel


-------------------Classes-------------------

I've never tried it with SE, but Classes would be incredibly useful when you've got multiple surfaces you're playing on, wouldn't it?

Boots 2:
-15 plastic
-1 low density structure

Brain 1:
-5 processing unit
-200 advanced neural gel
-5 steel plate

Brain 2:
-5 quantum processor
-200 advanced neural gel
-5 iridium plate

Gloves 2:
-5 heavy bearing
-5 beryllium plate

Head 2:
-1 brain 2
-5 beryllium plate

Power core:
-20 vitalic acid
-5 vitalic reagent
-2 vulcanite block
-2 cryonite rod
-5 low density structure

Character frame 1:
-8 big electric motor
-15 processing unit
-30 copper cable
-1 boots 1
-1 gloves 1
-1 head 1
-1 power core
-1 steel chest
-15 steel plate

Character frame 2:
-8 big electric motor
-5 quantum processor
-30 holmium cable
-1 boots 2
-1 gloves 2
-1 head 2
-1 power core
-1 steel chest
-5 steel plate
-10 aeroframe pole

Balanced 2 class character:
-1 character frame 2
-1 assembling machine 4

Builder 2 class character:
-1 character frame 2
-1 space manufactory

Engineer class character:
-1 character frame 2
-1 industrial furnace
-1 assembling machine 3

Fighter 2 class character:
-1 character frame 2
-1 assembling machine 3
-1 exoskeleton 2

Miner 2 class character:
-1 character frame 2
-1 thermodynamics facility
-1 assembling machine 3

Prospector class character:
-1 character frame 2
-1 industrial furnace
-1 exoskeleton 2

**Comment by mecejide** [comment]
I was thinking that the advanced resources would be after cargo rockets (and absent from Nauvis), but still required for the space sciences as ingredients.

**Comment by Qatavin** [comment]
So, something like gold in addition to holmium for energy science, tungsten and iridium for material science, and titanium and beryllium for astronomic science? Well, that might be possible. But setting up an offworld outpost takes a fair amount of time. If both materials were needed at the same time, that would practically force the player to limit their colonization targets to worlds that are rich in both materials. So, it would have to be something like beryllium before astronomic science 1, leading to the unlock of titanium after astronomic science 2. I suppose that could work. The production chains for titanium and such would have to be redone in order to make them of at least comparable complexity to the advanced SE materials.

Then, if nickel were repurposed as a component of electrical heating elements for electric furnaces and a few other things, like I outlined in the Science pack progression thread #69, and early rockets were limited to only needing aluminium, that would essentially let you get to space with only nickel, oil, aluminium, and maybe lithium to replace silver-zinc batteries. That seems fair enough. Silver and zinc could be added to utility and production science in some way, while still being available on Nauvis to avoid the problem I mentioned above about multiple outposts for a single science pack.

Gemstones are only needed for high level upgrades, so popping back down to Nauvis for them at a time when you probably haven't been doing much on your homeworld for a while sounds fine.

It's suggested in the design doc above that maybe Throium could be made available only offworld, which actually makes a fair amount of sense. It's easier to process than uranium, with no byproducts, so I guess it could be useful as an energy solution for outposts.

That's... That's everything! The entire list of ores! This scheme would still require reworking the recipes of nearly every final product in the game... But holy cow, this could actually work and still be fun.

**Comment by Qatavin** [comment]
-------------------Personal equipment-------------------

Portable solar panel 2:
-1 portable solar panel 1
-5 advanced circuit
-2 glass
-5 pyroflux

Portable solar panel 3:
-1 portable solar panel 2
-3 processing unit
-1 multispectral mirror
-2 holmium plate
-2 holmium cable

Portable solar panel 4:
-1 portable solar panel 3
-1 quantum processing unit
-2 superconductive cable
-10 alien artifact

Portable RTG 1:
-50 processing unit
-50 low density structure
-4 uranium fuel cell

Portable RTG 2: (utility science)
-4 portable RTG 1
-50 processing unit
-100 low density structure
-50 heat shielding
-20 cryonite rod
-+50 alien artifact

Portable fusion reactor 1: (energy science 1)
-100 processing unit
-50 low density structure
-50 heat shielding
-20 holmium cable
-10 electromagnetic field data
-200 plasma stream

Portable fusion reactor 2: (material/energy science 3)
-1 portable fusion reactor 1
-20 quantum processor
-50 superconductive cable
-10 magnetic canister
-10 atomic data
-1 efficiency module 6
-+15 orange alien artifact
-+15 blue alien artifact

Portable fusion reactor 3: (astro/bio/material/energy science 4)
-1 portable fusion reactor 2
-40 gamma ray detector
-20 dynamic emitter
-40 nanomaterial
-20 fusion test data
-1 productivity module 6
-+15 yellow alien artifact
-+15 purple alien artifact

Portable fusion reactor 4: (deep space science 3)
-1 portable fusion reactor 3
-5 naquium processor
-4 naquium cube
-20 naquium plate
-1 naquium energy data
-1 speed module 6
-+15 red alien artifact
-+15 green alien artifact

Personal battery 2:
-2 personal battery 1
-2 low density structure
-2 advanced circuit

Personal battery 3:
-2 personal battery 2
-1 vulcanite block
-1 cryonite block

Personal battery 4:
-2 personal battery 3
-5 holmium cable
-2 processing unit
-+5 orange alien artifact
-+5 blue alien artifact

Personal battery 5:
-2 personal battery 4
-2 beryllium plate
-2 iridium plate
-10 vitalic acid
-+5 yellow alien artifact
-+5 purple alien artifact

Personal battery 6:
-2 personal battery 5
-2 naquium cube
-2 nanomaterial
-2 superconductive cable
-+5 red alien artifact
-+5 green alien artifact

Exoskeleton 2:
-1 Exoskeleton 1
-10 processing unit
-16 aeroframe pole
-16 heavy bearing

Exoskeleton 3:
-1 exoskeleton 2
-40 neural gel
-12 holmium solenoid
-16 nanomaterial

Personal roboport robot control 1:
-5 advanced circuit

Personal roboport robot control 2:
-1 personal roboport robot control 1
-5 processing unit

Personal roboport robot control 3: (utility science)
-1 personal roboport robot control 2
-10 processing unit

Personal roboport robot control 4:
-1 personal roboport robot control 3
-1 quantum processor

Personal roboport 2: steel plate -> 5 beryllium plate
Personal roboport 3: steel plate -> 4 aeroframe scaffold
Personal roboport 4: steel plate -> 2 aeroframe bulkhead

Night vision: (color_lookup = {{0.5, "__core__/graphics/color_luts/nightvision.png"}})
Night vision 3: processing unit -> 10 neural gel

Personal laser defense 1:
-3 battery
-5 advanced circuit
-20 glass
-5 steel plate

Personal laser defense 2:
-1 personal laser defense 1
-40 cryonite slush
-10 advanced circuit
-2 low density structure

Personal laser defense 3:
-1 personal laser defense 2
-20 holmium cable
-5 processing unit
-5 holmium plate

Personal laser defense 4:
-1 personal laser defense 3
-4 multispectral mirror
-10 processing unit
-5 iridium plate

Personal laser defense 5:
-1 personal laser defense 4
-4 dynamic emitter
-1 quantum processor
-1 aeroframe bulkhead

Personal laser defense 6:
-1 personal laser defense 5
-1 naquium crystal
-3 quantum processor
-8 nanomaterial


-------------------Enemies-------------------

Large artefact
-1 small artifact
-1 experimental biomass
-10 methane gas

**Comment by mecejide** [comment]
Are you also going to cover the recipes that originate in SE?

**Comment by Qatavin** [comment]
Since these recipes were written assuming no Bob's plates materials, as that is the current state of mod compatibility, I wasn't planning on doing that right now. If I were, I would probably start by making a chart of where and when various materials are supposed to occur in the tech tree.

**Comment by mecejide** [comment]
MCI isn’t the only mod that would necessitate changes.

**Comment by KiwiHawk** [comment]
I'm sorry, I've not had the time to even start looking at this 🤷‍♂️

If you'd like to make a PR for it, I'd happily merge that in? 🙂

**Comment by Qatavin** [comment]
Probably not in the next couple days, but I expect I'll have plenty of time next week to take care of it.

**Comment by Qatavin** [comment]
I've been working on this recently. Or, kind of wrestling with it, really. SE has these clever algorithmic schemes for integrating other mods, some of which I see the point of, others not so much. They keep automatically giving technologies unwanted science packs that don't have anything to do with what's actually being used in the tech's recipes, and I can't figure out why. Can't always correct it either, since SE loads after Bob's - sometimes removing things in the data-final-fixes stage works, sometimes it doesn't. But I figure this could be solved if I add SE as an optional dependency. Would that be alright?

**Comment by KiwiHawk** [comment]
We could add SE as a hidden optional dependency, sure! However I'm guessing that the problematic changes are being made by SE Postprocessing mod. From that mod's description:

> If you are a mod maker and want to control the compatibility with your mod do not add this mod as a dependency, add the base Space Exploration mod instead and if changes made here are incompatible they can be removed.

https://mods.factorio.com/mod/space-exploration-postprocess

Mods which do try depend on SE PP have been known to get added to the incompatible list.

**Comment by Qatavin** [comment]
Making SE base an optional dependency worked, and the problems I was having were fixed easily enough. For the most part. Some took trying a couple different things before they stuck. It literally feels like SE is some kind of animal thrashing randomly against my efforts to corral it.
